[package]
name = "chapter-8-list-of-nums"
version = "0.1.0"
authors = ["Yury Herlovich"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
